import Navbar from "@/components/nav/nav";
import "@/styles/globals.css";
import { roboto } from "@/ui/font";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="no">
            <body className={roboto.className}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
